# Nome do workflow
name: COBOL Check Automation

# Aciona o workflow em push para a branch main
on:
  push:
    branches: [ main ]

jobs:
  cobol-check:
    runs-on: ubuntu-latest
    steps:
      # 1. Faz o checkout do repositório
      - uses: actions/checkout@v2

      # 2. Configura o ambiente Java
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          
      # 3. PASSO ATUALIZADO: Configura o ambiente no Mainframe e faz o Upload do COBOL Check
      # Este passo executa o script zowe_operations.sh que você criou
      - name: Setup Mainframe Environment and Upload COBOL Check
        env:
          ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
        run: |
          chmod +x .github/scripts/zowe_operations.sh
          .github/scripts/zowe_operations.sh

