# Nome do workflow
name: COBOL Check Automation

on:
  push:
    branches: [ main ]

jobs:
  coblog-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Install Zowe CLI
        run: npm install -g @zowe/cli@zowe-v2-lts

      - name: Add Mainframe Host Key to Known Hosts
        env:
          ZOWE_HOST: 204.90.115.200
          ZOWE_PORT: 22
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p $ZOWE_PORT -H $ZOWE_HOST >> ~/.ssh/known_hosts

      - name: Create and Set Zowe Default Profiles
        env:
          ZOWE_USER: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
          ZOWE_HOST: 204.90.115.200
          ZOWE_PORT: 22
        run: |
          # Inicializa o config.json sem credential store
          zowe config init -o

          # Define os dados de conexão
          zowe config set profiles.base.properties.host $ZOWE_HOST
          zowe config set profiles.base.properties.port $ZOWE_PORT
          zowe config set profiles.base.properties.user $ZOWE_USER
          zowe config set profiles.base.properties.password $ZOWE_PASSWORD

          # Marca o perfil base como default
          zowe config set defaults.base base

          # Apenas debug para ver config (opcional)
          zowe config list

      - name: Setup Mainframe Environment and Upload COBOL Check
        env:
          ZOWE_USER_FOR_SCRIPT: ${{ secrets.ZOWE_USERNAME }}
        run: |
          chmod +x .github/scripts/zowe_operations.sh
          .github/scripts/zowe_operations.sh

      - name: Run COBOL Check on Mainframe
        env:
          ZOWE_USER_FOR_SCRIPT: ${{ secrets.ZOWE_USERNAME }}
        run: |
          LOWERCASE_USER=$(echo "$ZOWE_USER_FOR_SCRIPT" | tr '[:upper:]' '[:lower:]')
          zowe zos-uss issue ssh "cd /z/$LOWERCASE_USER/cobolcheck && bash .github/scripts/mainframe_operations.sh"
