# Nome do workflow
name: COBOL Check Automation

# Aciona o workflow em push para a branch main
on:
  push:
    branches: [ main ]

jobs:
  cobol-check:
    runs-on: ubuntu-latest
    steps:
      # 1. Faz o checkout do repositório
      - uses: actions/checkout@v2

      # 2. Configura o ambiente Java
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      
      # 3. Instala a ferramenta Zowe CLI
      - name: Install Zowe CLI
        run: npm install -g @zowe/cli@zowe-v2-lts

      # 4. Cria e define os perfis Zowe padrão
      - name: Create and Set Zowe Default Profiles
        env:
          ZOWE_USER: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
          ZOWE_HOST: 204.90.115.200
          ZOWE_PORT: 22
        run: |
          # Cria e define como padrão o perfil para comandos SSH e USS
          # A opção --reject-unauthorized false lida com a verificação de impressão digital do SSH
          zowe profiles create ssh default --host $ZOWE_HOST --port $ZOWE_PORT --user $ZOWE_USER --password $ZOWE_PASSWORD --reject-unauthorized false --overwrite
          
          # Cria e define como padrão o perfil para comandos zos-files
          zowe profiles create zos-files default --host $ZOWE_HOST --port $ZOWE_PORT --user $ZOWE_USER --password $ZOWE_PASSWORD --reject-unauthorized false --overwrite

      # 5. Configura o ambiente no Mainframe e faz o Upload do COBOL Check
      - name: Setup Mainframe Environment and Upload COBOL Check
        env:
          ZOWE_USER_FOR_SCRIPT: ${{ secrets.ZOWE_USERNAME }}
        run: |
          chmod +x .github/scripts/zowe_operations.sh
          .github/scripts/zowe_operations.sh

      # 6. Executa o COBOL Check no Mainframe
      - name: Run COBOL Check on Mainframe
        env:
          ZOWE_USER_FOR_SCRIPT: ${{ secrets.ZOWE_USERNAME }}
        run: |
          LOWERCASE_USER=$(echo "$ZOWE_USER_FOR_SCRIPT" | tr '[:upper:]' '[:lower:]')
          # Este comando agora usa o perfil SSH 'default' automaticamente
          zowe zos-uss issue ssh "cd /z/$LOWERCASE_USER/cobolcheck && bash .github/scripts/mainframe_operations.sh"

