# Nome do workflow
name: COBOL Check Automation

# Aciona o workflow em push para a branch main
on:
  push:
    branches: [ main ]

jobs:
  coblog-check:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout
      - uses: actions/checkout@v2

      # 2. Setup Java
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      
      # 3. Install Zowe CLI
      - name: Install Zowe CLI
        run: npm install -g @zowe/cli@zowe-v2-lts

      # 4. Add Mainframe Host Key
      - name: Add Mainframe Host Key to Known Hosts
        env:
          ZOWE_HOST: 204.90.115.200
          ZOWE_PORT: 22
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p $ZOWE_PORT -H $ZOWE_HOST >> ~/.ssh/known_hosts

      # 5. *** ABORDAGEM RECOMENDADA: Configuração Explícita do Zowe V2 ***
      - name: Create and Set Zowe Default Profiles using V2 Config
        env:
          ZOWE_USER: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
          ZOWE_HOST: 204.90.115.200
        run: |
          # Inicializa a configuração do Zowe, desabilitando o uso do keyring do SO
          zowe config init --global-config --user-config --no-secure-credential-store

          # Cria um perfil "base" com as informações de conexão
          zowe config set "profiles.base.type" "zosmf" --global-config
          zowe config set "profiles.base.properties.host" "$ZOWE_HOST" --global-config
          
          # Define o usuário e a senha de forma segura dentro do arquivo de configuração do Zowe
          zowe config set "profiles.base.secure.user" "$ZOWE_USER" --secure --global-config
          zowe config set "profiles.base.secure.password" "$ZOWE_PASSWORD" --secure --global-config

          # Define o perfil "base" como padrão para todos os comandos
          zowe config set "defaults.zosmf" "base" --global-config
          zowe config set "defaults.ssh" "base" --global-config
          zowe config set "defaults.files" "base" --global-config

          echo "Zowe V2 config created successfully without OS keyring."
          # Opcional: Verifique a configuração (não mostra a senha)
          zowe config list --global-config

      # 6. Setup Mainframe Environment
      - name: Setup Mainframe Environment and Upload COBOL Check
        env:
          ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
        run: |
          chmod +x .github/scripts/zowe_operations.sh
          .github/scripts/zowe_operations.sh

      # 7. Run COBOL Check
      - name: Run COBOL Check on Mainframe
        env:
          ZOWE_USER_FOR_SCRIPT: ${{ secrets.ZOWE_USERNAME }}
        run: |
          LOWERCASE_USER=$(echo "$ZOWE_USER_FOR_SCRIPT" | tr '[:upper:]' '[:lower:]')
          # O Zowe usará automaticamente o perfil padrão configurado no passo 5
          zowe zos-uss issue ssh "cd /z/$LOWERCASE_USER/cobolcheck && bash .github/scripts/mainframe_operations.sh"
